[mypy]
plugins = sqlalchemy.ext.mypy.plugin
strict = true
ignore_missing_imports = false
warn_unused_ignores = true

[mypy-firebase_admin]
ignore_missing_imports = true

[mypy-firebase_admin.*]
ignore_missing_imports = true

[mypy-google.cloud]
ignore_missing_imports = true

[mypy-google.cloud.*]
ignore_missing_imports = true

[mypy-googlemaps]
ignore_missing_imports = true

[mypy-googlemaps.*]
ignore_missing_imports = true

[mypy-pandas]
ignore_missing_imports = true

[mypy-pandas.*]
ignore_missing_imports = true

[mypy-prophet]
ignore_missing_imports = true

[mypy-prophet.*]
ignore_missing_imports = true

[mypy-sklearn]
ignore_missing_imports = true

[mypy-sklearn.*]
ignore_missing_imports = true

[mypy-app.api.v1.*]
ignore_errors = true

[mypy-app.core.security]
ignore_errors = true

[mypy-app.db.models.*]
ignore_errors = true

[mypy-app.firebase.*]
ignore_errors = true

[mypy-app.ml.*]
ignore_errors = true

[mypy-app.services.cache_service]
ignore_errors = true

[mypy-app.services.notification_service]
ignore_errors = true

[mypy-app.services.translation_service]
ignore_errors = true
