import type { ZoneDensity } from '@/types/crowd';
import type { MenuItem } from '@/types/order';
import type { QueueState } from '@/types/queue';
import type { Venue } from '@/types/venue';

function zoneIdByType(venue: Venue | null, zoneType: string, fallbackIndex = 0): string | null {
  if (!venue) {
    return null;
  }

  const matches = venue.zones.filter(
    (zone) => (zone.zone_type ?? zone.zoneType ?? '').toLowerCase() === zoneType
  );

  return matches[fallbackIndex]?.id ?? venue.zones[fallbackIndex]?.id ?? null;
}

export function buildDemoQueues(venue: Venue | null): QueueState[] {
  const venueId = venue?.id ?? 'demo-venue';
  const now = new Date().toISOString();

  return [
    {
      id: 'demo-queue-1',
      venueId,
      venue_id: venueId,
      zoneId: zoneIdByType(venue, 'entry'),
      zone_id: zoneIdByType(venue, 'entry'),
      name: 'Main Gate Security',
      queueType: 'entry',
      queue_type: 'entry',
      isOpen: true,
      is_open: true,
      estimatedWaitMinutes: 6,
      estimated_wait_minutes: 6,
      wait_minutes: 6,
      currentLength: 34,
      current_length: 34,
      throughputPerMinute: 7,
      annotation: 'Fastest entry lane right now',
      lastUpdated: now,
      last_updated: now,
    },
    {
      id: 'demo-queue-2',
      venueId,
      venue_id: venueId,
      zoneId: zoneIdByType(venue, 'food'),
      zone_id: zoneIdByType(venue, 'food'),
      name: 'Food Court A Express',
      queueType: 'food',
      queue_type: 'food',
      isOpen: true,
      is_open: true,
      estimatedWaitMinutes: 8,
      estimated_wait_minutes: 8,
      wait_minutes: 8,
      currentLength: 22,
      current_length: 22,
      throughputPerMinute: 5,
      annotation: 'Pickup priority for mobile orders',
      lastUpdated: now,
      last_updated: now,
    },
    {
      id: 'demo-queue-3',
      venueId,
      venue_id: venueId,
      zoneId: zoneIdByType(venue, 'concourse'),
      zone_id: zoneIdByType(venue, 'concourse'),
      name: 'East Concourse Snacks',
      queueType: 'food',
      queue_type: 'food',
      isOpen: true,
      is_open: true,
      estimatedWaitMinutes: 11,
      estimated_wait_minutes: 11,
      wait_minutes: 11,
      currentLength: 28,
      current_length: 28,
      throughputPerMinute: 4,
      annotation: 'Best for drinks and quick snacks',
      lastUpdated: now,
      last_updated: now,
    },
    {
      id: 'demo-queue-4',
      venueId,
      venue_id: venueId,
      zoneId: zoneIdByType(venue, 'seating'),
      zone_id: zoneIdByType(venue, 'seating'),
      name: 'North Stand Restrooms',
      queueType: 'restroom',
      queue_type: 'restroom',
      isOpen: true,
      is_open: true,
      estimatedWaitMinutes: 4,
      estimated_wait_minutes: 4,
      wait_minutes: 4,
      currentLength: 10,
      current_length: 10,
      throughputPerMinute: 8,
      annotation: 'Shortest restroom queue right now',
      lastUpdated: now,
      last_updated: now,
    },
    {
      id: 'demo-queue-5',
      venueId,
      venue_id: venueId,
      zoneId: zoneIdByType(venue, 'seating', 1),
      zone_id: zoneIdByType(venue, 'seating', 1),
      name: 'South Stand Merchandise',
      queueType: 'merchandise',
      queue_type: 'merchandise',
      isOpen: true,
      is_open: true,
      estimatedWaitMinutes: 9,
      estimated_wait_minutes: 9,
      wait_minutes: 9,
      currentLength: 16,
      current_length: 16,
      throughputPerMinute: 3,
      annotation: 'Official team merchandise and scarves',
      lastUpdated: now,
      last_updated: now,
    },
    {
      id: 'demo-queue-6',
      venueId,
      venue_id: venueId,
      zoneId: zoneIdByType(venue, 'concourse', 1),
      zone_id: zoneIdByType(venue, 'concourse', 1),
      name: 'West Concourse Info Desk',
      queueType: 'information',
      queue_type: 'information',
      isOpen: true,
      is_open: true,
      estimatedWaitMinutes: 3,
      estimated_wait_minutes: 3,
      wait_minutes: 3,
      currentLength: 6,
      current_length: 6,
      throughputPerMinute: 6,
      annotation: 'Help desk and accessibility guidance',
      lastUpdated: now,
      last_updated: now,
    },
    {
      id: 'demo-queue-7',
      venueId,
      venue_id: venueId,
      zoneId: zoneIdByType(venue, 'entry'),
      zone_id: zoneIdByType(venue, 'entry'),
      name: 'Medical Assistance',
      queueType: 'medical',
      queue_type: 'medical',
      isOpen: true,
      is_open: true,
      estimatedWaitMinutes: 2,
      estimated_wait_minutes: 2,
      wait_minutes: 2,
      currentLength: 2,
      current_length: 2,
      throughputPerMinute: 2,
      annotation: 'On-call first aid support',
      lastUpdated: now,
      last_updated: now,
    },
  ];
}

export function buildDemoMenu(venueId: string): MenuItem[] {
  return [
    {
      id: 'demo-menu-1',
      venueId,
      venue_id: venueId,
      name: 'Grilled Chicken Wrap',
      description: 'Tender grilled chicken, lettuce, tomato, and garlic sauce in a wheat tortilla.',
      price: 249,
      category: 'mains',
      dietaryTags: ['halal'],
      dietary_tags: ['halal'],
      imageUrl: null,
      image_url: null,
      prepTimeMinutes: 7,
      prep_time_minutes: 7,
      isAvailable: true,
      is_available: true,
      isSoldOut: false,
      is_sold_out: false,
    },
    {
      id: 'demo-menu-2',
      venueId,
      venue_id: venueId,
      name: 'Paneer Tikka Roll',
      description: 'Spiced cottage cheese with onions and mint chutney wrapped in a fresh roti.',
      price: 199,
      category: 'mains',
      dietaryTags: ['vegetarian'],
      dietary_tags: ['vegetarian'],
      imageUrl: null,
      image_url: null,
      prepTimeMinutes: 6,
      prep_time_minutes: 6,
      isAvailable: true,
      is_available: true,
      isSoldOut: false,
      is_sold_out: false,
    },
    {
      id: 'demo-menu-3',
      venueId,
      venue_id: venueId,
      name: 'Stadium Burger',
      description: 'Juicy chicken patty with stadium-special sauce, pickles, and crispy lettuce.',
      price: 299,
      category: 'mains',
      dietaryTags: ['halal'],
      dietary_tags: ['halal'],
      imageUrl: null,
      image_url: null,
      prepTimeMinutes: 8,
      prep_time_minutes: 8,
      isAvailable: true,
      is_available: true,
      isSoldOut: false,
      is_sold_out: false,
    },
    {
      id: 'demo-menu-4',
      venueId,
      venue_id: venueId,
      name: 'Veg Hot Dog',
      description: 'Plant-based sausage with mustard, ketchup, and grilled onions in a soft bun.',
      price: 149,
      category: 'mains',
      dietaryTags: ['vegetarian', 'vegan'],
      dietary_tags: ['vegetarian', 'vegan'],
      imageUrl: null,
      image_url: null,
      prepTimeMinutes: 5,
      prep_time_minutes: 5,
      isAvailable: true,
      is_available: true,
      isSoldOut: false,
      is_sold_out: false,
    },
    {
      id: 'demo-menu-5',
      venueId,
      venue_id: venueId,
      name: 'Masala Chips',
      description: 'Crispy potato chips with spiced masala seasoning and chaat masala.',
      price: 149,
      category: 'snacks',
      dietaryTags: ['vegetarian', 'vegan'],
      dietary_tags: ['vegetarian', 'vegan'],
      imageUrl: null,
      image_url: null,
      prepTimeMinutes: 3,
      prep_time_minutes: 3,
      isAvailable: true,
      is_available: true,
      isSoldOut: false,
      is_sold_out: false,
    },
    {
      id: 'demo-menu-6',
      venueId,
      venue_id: venueId,
      name: 'Samosa (2 pcs)',
      description: 'Crisp pastry filled with spiced potatoes and peas, served with green chutney.',
      price: 80,
      category: 'snacks',
      dietaryTags: ['vegetarian'],
      dietary_tags: ['vegetarian'],
      imageUrl: null,
      image_url: null,
      prepTimeMinutes: 2,
      prep_time_minutes: 2,
      isAvailable: true,
      is_available: true,
      isSoldOut: false,
      is_sold_out: false,
    },
    {
      id: 'demo-menu-7',
      venueId,
      venue_id: venueId,
      name: 'Nachos with Salsa',
      description: 'Corn tortilla chips with house-made tomato salsa and sour cream.',
      price: 179,
      category: 'snacks',
      dietaryTags: ['vegetarian', 'gluten-free'],
      dietary_tags: ['vegetarian', 'gluten-free'],
      imageUrl: null,
      image_url: null,
      prepTimeMinutes: 3,
      prep_time_minutes: 3,
      isAvailable: true,
      is_available: true,
      isSoldOut: false,
      is_sold_out: false,
    },
    {
      id: 'demo-menu-8',
      venueId,
      venue_id: venueId,
      name: 'Popcorn Combo',
      description: 'Large salted popcorn with a refillable soft drink.',
      price: 129,
      category: 'snacks',
      dietaryTags: ['vegetarian', 'vegan'],
      dietary_tags: ['vegetarian', 'vegan'],
      imageUrl: null,
      image_url: null,
      prepTimeMinutes: 2,
      prep_time_minutes: 2,
      isAvailable: true,
      is_available: true,
      isSoldOut: false,
      is_sold_out: false,
    },
    {
      id: 'demo-menu-9',
      venueId,
      venue_id: venueId,
      name: 'Cold Cola',
      description: 'Chilled carbonated cola drink, 500ml.',
      price: 99,
      category: 'beverages',
      dietaryTags: ['vegan'],
      dietary_tags: ['vegan'],
      imageUrl: null,
      image_url: null,
      prepTimeMinutes: 1,
      prep_time_minutes: 1,
      isAvailable: true,
      is_available: true,
      isSoldOut: false,
      is_sold_out: false,
    },
    {
      id: 'demo-menu-10',
      venueId,
      venue_id: venueId,
      name: 'Lemon Nimbu Pani',
      description: 'Freshly squeezed lemon water with mint and a pinch of salt.',
      price: 60,
      category: 'beverages',
      dietaryTags: ['vegetarian', 'vegan'],
      dietary_tags: ['vegetarian', 'vegan'],
      imageUrl: null,
      image_url: null,
      prepTimeMinutes: 2,
      prep_time_minutes: 2,
      isAvailable: true,
      is_available: true,
      isSoldOut: false,
      is_sold_out: false,
    },
    {
      id: 'demo-menu-11',
      venueId,
      venue_id: venueId,
      name: 'Mango Lassi',
      description: 'Chilled creamy mango yoghurt drink, a crowd favourite.',
      price: 89,
      category: 'beverages',
      dietaryTags: ['vegetarian'],
      dietary_tags: ['vegetarian'],
      imageUrl: null,
      image_url: null,
      prepTimeMinutes: 2,
      prep_time_minutes: 2,
      isAvailable: true,
      is_available: true,
      isSoldOut: false,
      is_sold_out: false,
    },
    {
      id: 'demo-menu-12',
      venueId,
      venue_id: venueId,
      name: 'Masala Chai',
      description: 'Spiced Indian milk tea, served hot in a paper cup.',
      price: 49,
      category: 'beverages',
      dietaryTags: ['vegetarian'],
      dietary_tags: ['vegetarian'],
      imageUrl: null,
      image_url: null,
      prepTimeMinutes: 3,
      prep_time_minutes: 3,
      isAvailable: true,
      is_available: true,
      isSoldOut: false,
      is_sold_out: false,
    },
  ];
}

export function buildDemoZoneDensities(venue: Venue | null): ZoneDensity[] {
  if (!venue) {
    return [];
  }

  return venue.zones.map((zone) => {
    const density = Number(zone.current_density ?? zone.currentDensity ?? 0);
    const level = String(zone.density_level ?? zone.densityLevel ?? 'LOW').toUpperCase() as ZoneDensity['level'];
    const lat = zone.lat_center ?? zone.latCenter ?? 0;
    const lng = zone.lng_center ?? zone.lngCenter ?? 0;

    return {
      id: zone.id,
      zoneId: zone.id,
      venueId: venue.id,
      venue_id: venue.id,
      name: zone.name,
      zoneName: zone.name,
      zone_name: zone.name,
      zone_type: zone.zone_type ?? zone.zoneType ?? null,
      density,
      current_density: density,
      level,
      density_level: level,
      count: Number(zone.current_count ?? zone.currentCount ?? 0),
      isOpen: Boolean(zone.is_open ?? zone.isOpen ?? true),
      is_open: Boolean(zone.is_open ?? zone.isOpen ?? true),
      updatedAt: null,
      updated_at: null,
      latCenter: lat,
      lat_center: lat,
      lngCenter: lng,
      lng_center: lng,
      polygon: zone.polygon ?? null,
      center_point: { latitude: lat, longitude: lng },
    };
  });
}
